### ISSUE TITLE
Session Graph is empty

### ISSUE THREAD

**Issue by shashi94310** [codeRimoe/DL_for_RSIs#2]
While executing the code for experiment.ipynb, it's giving the error as "The Session graph is empty. Add operations to the graph before calling run()." Can you please tell how to add the operation to it.

**Comment by codeRimoe** [comment]
This project is based on Tensorflow v1, please refer to the code environment. If you want to use Tensorflow v2 to run the scripts, you need to modify the code, and this link might be helpful for you: 

[[How to fix ‘RuntimeError: The Session graph is empty. Add operations to the graph before calling run().”](https://stackoverflow.com/questions/57206247/how-to-fix-runtimeerror-the-session-graph-is-empty-add-operations-to-the-grap)](https://stackoverflow.com/questions/57206247/how-to-fix-runtimeerror-the-session-graph-is-empty-add-operations-to-the-grap)
