### ISSUE TITLE
Accuracy used

### ISSUE THREAD

**Issue by shashi94310** [codeRimoe/DL_for_RSIs#3]
Can you please tell which accuracy you have used as overall accuracy in the paper. Because in your experiment.ipynb program you have executed for st_ss_pGRU and the training accuracy is popping according to your program as (0.847656*100) % but in paper under overall accuracy table you have mentioned 90.35%. if possible, please provide the code to calculate this accuracy. Thank you.

**Comment by codeRimoe** [comment]
Dear shashi,

Sorry for the very late response.

OA = correctly_predicted_sample_number / sample_number

Regarding the outputs, they do not correspond to the results of the experiments mentioned in the paper. However, the model itself is indeed reliable. I re-ran the code and have uploaded a corrected notebook with updated outputs.

The outputs are not the results of the experiments in the paper. However, the model itself is indeed reliable. I have re-run the code and have uploaded a corrected notebook with updated outputs. The code runs the experiment 10 times, and the test OA is around 0.88. It’s worth noting that in some instances, the training OA was relatively low (around 0.90), leading to a lower test OA. This indicates that the model is underfitting.  The results are influenced by the random seed and the number of training epochs. Adjusting the training epochs may yield a model with improved performance.
